language: cpp
dist: trusty
sudo: false

matrix:
  include:
    # GCC 6
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

      after_success:
        - pip install --user cpp-coveralls
        - coveralls -r .. --gcov-options '\-lp' --exclude build/CMakeFiles

    # Clang / Xcode 8
    - os: osx
      osx_image: xcode8

before_install:
    - eval "${MATRIX_EVAL}"

install:
  # mkdir
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  # install cmake
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake || brew install cmake
    fi
  - cmake --version

before_script:
  # CMake => Makefile (debug)
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug

script:
  - make LeviDB -j2 && ./LeviDB